openapi: 3.0.0
info:
  title: Learnify API
  version: 1.0.0
paths:
  /api/auth/signin:
    post:
      summary: User sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login
        401:
          description: Unauthorized

  /api/assessments:
    get:
      summary: Get all assessments
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: difficulty
          schema:
            type: string
        - in: query
          name: type
          schema:
            type: string
      responses:
        200:
          description: List of assessments
        401:
          description: Unauthorized 